### ISSUE TITLE
More complex toggling

### ISSUE THREAD

**Issue by smichel17** [LibreShift/red-moon#106]
My filter turns on at sunset. Later, when I get into bed, I change it to `bed reading`. Then it automatically turns off in the morning.

The next evening, when it turns on again, I'd really like it to turn on using the `default` filter, not the `bed reading` filter.

I'm thinking of a UX kind of like this timer:

<img alt="timer" src="https://cloud.githubusercontent.com/assets/6563664/22387677/cdf7ae8c-e4aa-11e6-9ba1-bb4e31f83dd0.jpg" height="400" align="right">

- You can insert or remove pins at certain times to make a custom toggle pattern (blue boxes).
  - We could have a + button, where you can create a new event. That event could be "turn off the filter" or "set the filter to `default`".
- You can spin the plastic piece (red box) to manually toggle.
  - This is like manually starting or stopping the timer with the fab (or switch, not sure which I prefer).
- Instead of having a preference to toggle location, you can add an event that toggles to a certain filter at sunset.
  - We can include an option in the menu to automatically create an 'on' event at sunset and 'off' event at sunrise.

---

Steps:

- [ ] Remove the "times from sun" setting and make "sunset" and "sunrise" be options when picking the on and off time
- [ ] Change profile storage so that profiles are referenced by their settings, not their name or order in the list, so that the timer won't break if someone deletes a scheduled profile
- [ ] Add the ability to add and delete timer events
- [ ] Maybe: Add the ability to reset the timer to the defaults (sunset to sunrise)

**Comment by raatmarien** [comment]
I really like this idea, it seems like a very powerful feature. The only problem I see, is that it might be a lot of work to get it working (which I don't have time for), but if anyone can implement this, that would be great.

**Comment by smichel17** [comment]
>The only problem I see, is that it might be a lot of work to get it working (which I don't have time for)

At the moment, I'm in the same boat.

**Comment by smichel17** [comment]
Comment by @siltaar in #33 is good context for why this feature would be useful.

> I did set automatic times at : 22h turn-on ; 08h turn-off.
> It was night outside at 22h, but I had lights turned on in my living place…
> At 8h it was already bright outside, but my eyes were expecting small lights to look at.
> 
> In sun time, I can't tell if it was really synced with the actual light outsides. I'm waiting for an update to get feedback from the app about this feature.
> 
> Now, I disabled the dim feature, as it's usefull only when no other lights are on around, and it's not my case, so when the phone reboots, I just urge to disable Red Moon to be able to use the phone.
> 
> On the contrary, I like RedShift on Linux because is is limitating with an upper value the screen color temp even at mid-day.
> 
> So I finally have 4 needs :
> 
>     exceptional times : normal image (to watch details in photos, install apk…)
>     day time (with sun outside and no lights in) : need an already-reddish max-bright-screen value to get slightly red shifted screen all the time(so slightly relaxing eyes all the time)
>     evening time (without sun, but few lights in) : need the full red but no dim
>     night time (without sun, without lights) : need full red and dim (until I fully wake up…)
> 
> It could be possible to go in a continues process from a midday red value to full red at night, then full red and dim, and cycle everything back… Would allow to know which time is it, just by the color of the screen ^_^
> 
> Or, with current implementation, decide time bounds for intensity variation (or like RedShift, color variation from red to yellow), and separate time bounds for dim variation. It would do the trick for me I think.
> 
> (after that, if RedMoon could accept a setting like : secondary time bound to stop dim feature = time when next alarm will ring ; it would be perfect !)

**Comment by Siltaar** [comment]
> (after that, if RedMoon could accept a setting like : secondary time bound to stop dim feature = time when next alarm will ring ; it would be perfect !)

In fact it should be : next ringing alarm + 5 minutes (to be able to look at the phone and stop the alarm for instance… before getting full light from phone screen)

**Comment by smichel17** [comment]
The way forward on this is slowly becoming more clear.

We are not far away from removing the `times from sun` option entirely -- we'd still keep the functionality, it would just be tied to on and off: in addition to manually selecting a time, you could select `sunset` or `sunrise` for each one individually. This would allow you to have Red Moon turn off at sunrise and also have use a custom time for turning on.

At that point, although it would require significant backend changes, it would be another small UI change to allow adding more than 2 toggle times, and to choose which profile use at each point.

**Comment by smichel17** [comment]
Draft of layout for this screen (placeholder names):

Config
- Sunset [time]
- Sunrise [time]
- Calculate from location [toggle]
Schedule (list of events, tap to edit or delete)
- event: sunset -> start(profile)
- event: time -> start(profile)
- event: sunrise -> stop
Fab: Add event

**Comment by smichel17** [comment]
I suspect that this is more of a kludge/workaround for the fact that there is no transition period yet (#98). So, I am closing it until that issue is done, with milestone someday/maybe so I can find it again later.
