### ISSUE TITLE
Screen is not filtered on first turn on

### ISSUE THREAD

**Issue by smichel17** [LibreShift/red-moon#136]
Observed on a friend's device on v2.10.2, android 5.1.1.

After installing the app, the very first time the switch was toggled, the filter was not displayed. Toggling off and then on again made it work.

**Comment by matteocoder** [comment]
Can confirm also on version 3.0.0 on Moto G4 with Android 7.0

The app starts but the filter is not applied. A workaround is to go into the app and move any of the sliders.

**Comment by j710** [comment]
Confirmed on two devices (version 3.0.0) both BB Priv running Android 6.0.1. Agree with @matteocoder, touching a slider kicks it on.

**Comment by smichel17** [comment]
As far as I remember, this bug was introduced when I started using the top switch to toggle instead of the FAB. In v4.0.0 (not yet released) we're back to toggling using the FAB so I'm hoping that this bug is simply gone without me having to track down a specific fix :)

If anyone would like to test it, you can build from master yourself or grab the debug apk below.

Apologies for http link, you can use the same link with https if you want to accept my expired cert (my hosting provider's setup requires a manual action for using a new cert, so when combined with letsencrypt certs only lasting 90 days, I often let it lapse :/).

http://smichel.me/files/red-moon/red-moon-debug-2020-03-19.apk

**Comment by matteocoder** [comment]
Hello @smichel17 , using the FAB the filter toggles immediately. I'm still using my trusty G4, but on this time on 8.1.

**Comment by smichel17** [comment]
Thanks for testing :). Tentatively closing this and will re-open if we get any more reports.
