### ISSUE TITLE
Unable to purchase from Play Store

### ISSUE THREAD

**Issue by itsamenathan** [LibreShift/red-moon#148]
I receive the following error when trying to purchase this app. `Transaction was declined. [BM-CPEC-02]`

- URL: https://play.google.com/store/apps/details?id=com.jmstudios.redmoon
- Payment Method: Google Pay balance
- Phone: OnePlus One
- ROM: https://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-13-0-t3242700

**Comment by tmbgreaves** [comment]
I am getting the same error - this appears to affect multiple users and multiple payment methods. Spoke with google this morning to follow up on my error and they suggested bug reporting to developer (hence comment here)

**Comment by raatmarien** [comment]
Hey guys, thanks for letting me know about this. Unfortunately, I've hit a bit of a problem with Google Support telling me that the user should contact them, although they tell you you should contact me.

Anyway, to further troubleshoot, could you try to buy Red Moon with a promo code from Google Play (I've send you one through email) @itsamenathan , so I know if the trouble is with the payment part or the actually downloading the app. Thanks in advance!

**Comment by itsamenathan** [comment]
@raatmarien the promo code you gave me worked without issue.

**Comment by smichel17** [comment]
We've finally figured out the issue. It's a bit tricky to resolve, but hopefully will be in the next few weeks.

**Comment by smichel17** [comment]
@raatmarien  At this point I think it would be best if you just take Red Moon off the Play Store (or make it unlisted, or something like that). If someone else wants to handle releases there, we can link to them.

**Comment by smichel17** [comment]
See https://github.com/LibreShift/red-moon/issues/274#issuecomment-918185093
