### ISSUE TITLE
Give translators credit in the app

### ISSUE THREAD

**Issue by smichel17** [LibreShift/red-moon#154]
- [x] Add `translators` string 
- [x] Display translators on the about screen

**Comment by mueller-ma** [comment]
The app mysplash has a very beautiful about screen with small language flags, github avatars and when you tab on an name you get to the github page of this user

**Comment by smichel17** [comment]
@mueller-ma Is that this? https://github.com/WangDaYeeeeee/Mysplash

**Comment by mueller-ma** [comment]
Yes
![screenshot_20170909-202959](https://user-images.githubusercontent.com/22525368/30243222-67e57eb0-95a5-11e7-9188-23789a3f9d08.png)

**Comment by smichel17** [comment]
It looks nice. I'll take a look and see if I can easily re-use their code :)

**Comment by smichel17** [comment]
Okay, we can't do the same thing as them, since they're loading the avatars directly from github (red moon doesn't and never will request internet permission), and they use a lot of libraries that I don't want to introduce into red moon for something this simple.

However, I can re-use the layout itself, and just write my own code to set the images and text.

**Comment by mueller-ma** [comment]
F-Droid might not like the profile pictures included, because they are not free.

**Comment by smichel17** [comment]
Good point. An alternative is to ask you all what [flo](https://wiki.snowdrift.coop/about/free-libre-open) image you'd like, and generate [identicons](https://f-droid.org/packages/com.germainz.identiconizer/) for people who don't respond. Or use names and flags only.

**Comment by comradekingu** [comment]
If you make a field in the local branches of translation, wherein translators can add themselves along with a point of contact for corrections, no larger scale effort will have to take place.

**Comment by smichel17** [comment]
If I do it that way, it'll be easier to support showing the main translator but harder to show a list of all translators. I suppose what people care about most is the person(s) who actually translated it into their language, so this is reasonable. I'll add the string.

**Comment by mueller-ma** [comment]
Think about other contributors. They are also important

**Comment by smichel17** [comment]
>Think about other contributors. They are also important

In Red Moon's specific case, the vast majority of contributions have been translations (@joonatoona with upcoming root mode support might be the only exception), so right now I'm primarily concerned with giving them credit.

Agreed that all contributors are important; I made the string a list, so anyone who translates can add their name. It's currently less prominent than I'd like; in the future, I'm interested in identifying the main contributor(s) for each language, like mysplash does. Currently my time is a bit limited, so this was an easy way to get everyone's name in quickly so I can give you all *some* of the credit you deserve right away.

Going forward I've started and will continue to give people credit in the changelogs as well, for whatever form of contribution.

**Comment by comradekingu** [comment]
If the string says "DO NOT TRANSLATE, READ: add a list of current translators and past translators following this format.
Name Surname <email@domain.tld>,
Name2 Surname2 <email2@domain.tld>,

**Comment by smichel17** [comment]
> author field of the app

I'm either unfamiliar with what you mean or unsure of what you are suggesting. Could you clarify?

**Comment by comradekingu** [comment]
About/Contributions.

**Comment by smichel17** [comment]
I'm still not quite sure I understand. The about screen doesn't really have an author section right now, unless the email field counts?

**Comment by comradekingu** [comment]
Right, but wherever this contact info/credit section would be put.

**Comment by smichel17** [comment]
Yeah, it'd go on the about screen. Everything is build using preferences right now and I haven't tried dynamically generating them before, so it's a bit of extra work (which is why I went with the quick and easy translatable solution for now).

Just to confirm, you'd want your contact info in the app?

**Comment by comradekingu** [comment]
Yes, makes it easier to reach out in the event a mistake should have been made.

**Comment by smichel17** [comment]
The alternative is: you could share emails privately with me and/or hang around in the chat room, and I can ping you there. I agree, it would also be nice if I had a reliable way to ping you all before I make a release.

**Comment by smichel17** [comment]
For example, [here](https://github.com/raatmarien/red-moon/commit/cd1178bd7ce78066a3b65c1e820ad32119d3ce49#diff-01dafb3fd0217441330103cfc8300094R69) there's a new string where you should NOT translate `%on` and `%off`, as those will be substituted with the on and off times, but I'm not sure how to communicate that to everyone.

**Comment by comradekingu** [comment]
You can have that explained in a string comment. I am in the IRC btw.

**Comment by comradekingu** [comment]
Looks like weblate has it all automated https://docs.weblate.org/en/latest/devel/reporting.html#translator-credits

**Comment by smichel17** [comment]
> You can have that explained in a string comment.

It used to be very easy to miss string comments in Weblate. However, it looks like they have changed their interface (now they display string comments very prominently), so this is a good option.

**Comment by smichel17** [comment]
The original goal of this issue was included in v3.3.0, so I'm going to close this. I created #205 for the rest.
