### ISSUE TITLE
Provide direct download link of latest build 

### ISSUE THREAD

**Issue by jerryn70** [LibreShift/red-moon#177]
There is no .apk file for the latest released versions in the release section of GitHub .

**Comment by smichel17** [comment]
That's because I did the release. The previously-released apks are signed by @raatmarien, and Android will only let you upgrade if the app has the same signature. If I released you'd have to uninstall and reinstall. 

I think @raatmarien said in the chat room that he's on vacation right now or something, I just didn't want to wait for him to get back.

**Comment by dcorking** [comment]
Is this the same reason the 3.1.1 and 3.1.2 releases aren't on F-Droid yet? (Latest on F-Droid is 3.1.0 that crashes on old devices. Latest on Play store seems to be 3.0.0) 

If not would you like me to post an issue requesting releases to the app stores?

**Comment by smichel17** [comment]
> Is this the same reason the 3.1.1 and 3.1.2 releases aren't on F-Droid yet?

No, F-Droid builds themselves and signs with their own key (you'll notice v3.1.0 also has no apk).

> If not would you like me to post an issue requesting releases to the app stores?

This issue is good enough to track that :)

**Comment by dcorking** [comment]
F-Droid update: 3.1.1 and 3.1.2 APKs [shipped on Monday](https://f-droid.org/packages/com.jmstudios.redmoon/) : the app and the toggle widget both work really well for me on Android 4.4.4. Thanks all. 🌟  ( @jerryn70 I hope you don't have to wait long for the project's own signed build 😄 )

**Comment by jerryn70** [comment]
@dcorking but I need to uninstall current version to upgrade to the latest version. I don't want to loose my filter settings. that why I'm waiting

**Comment by smichel17** [comment]
@jerryn70 in the meantime, if you'd like you can use a debug version, which installs alongside the version from f-droid. I upload them periodically here (just did one now): http://smichel.me/files/red-moon/

Note: link is http, also will work https, but my cert is expired so you'll have to click through that, sorry.

**Comment by smichel17** [comment]
v3.2.0 is added now :)
