### ISSUE TITLE
Four preconfigured custom filter

### ISSUE THREAD

**Issue by mueller-ma** [LibreShift/red-moon#182]
I have removed all app data and now I have 4 times the same filter all called "Custom". Also when I change the filter and reset to default, nothing happens.

Oneplus X
Red Moon 3.1.2
Android 7.1.2
Lineageos 14.1

**Comment by smichel17** [comment]
Fixed in 8034891.

**Comment by smichel17** [comment]
As a workaround, I believe the names will load correctly if you close Red Moon and clear it from the recent apps each time you add a new filter.

**Comment by smichel17** [comment]
@mueller-ma v3.2.0 is out now, is this resolved?

**Comment by mueller-ma** [comment]
I now have "custom", "default", "dim only" and "reading", but I dont understand the menu entry "reset default filter"

**Comment by smichel17** [comment]
What locale are you using? It should say "*Restore* default filters" -- the function is to add back those 3 filters if you have deleted them.

**Comment by mueller-ma** [comment]
Ahhh. That makes sense.
I'm having it in German.
