### ISSUE TITLE
Add more contrast to the on/off toggle

### ISSUE THREAD

**Issue by ghost** [LibreShift/red-moon#199]
The on/off toggle in the upper right can be hard to spot, especially in a brighter surrounding when the screen is dimmed:
 
![image](https://user-images.githubusercontent.com/164785/31257106-feb9f730-aa36-11e7-8789-f561ad9f2800.png)

I would propose to raise the contrast of the UI elements.

**Comment by smichel17** [comment]
I agree with the issue; I'm slightly more inclined to change the ui component (ex: use a FAB or a simple menu item) instead, since switches in the action bar is non-standard behavior on android and theming is generally a PITA.

**Comment by smichel17** [comment]
Removed and changed to a FAB in the next release.
