### ISSUE TITLE
Saving filters under the same name

### ISSUE THREAD

**Issue by cyt-b6f** [LibreShift/red-moon#211]
Saving a filter setting under the same name as an already existing filter adds it to the filter list. Both filters have the same name but only the settings of the previously existing filter are present for both entries. Behavior should be when trying to save a filter with the same name as an existing filter either:
a) force saving filter setting under a different name
b) overwrite existing filter settings with new settings after user warning
c) include prompt with option to do a) or b)

Running v3.3.2 with Android 7.1.1

**Comment by smichel17** [comment]
Agreed; I'd like to do (a).

I'll get it to it in a week or two, when finals are over. It'd also a good first PR (very isolated from other code), if anyone's interested.

**Comment by smichel17** [comment]
Closed by #211
