### ISSUE TITLE
Enable schedule stop time while disabling start time

### ISSUE THREAD

**Issue by cyt-b6f** [LibreShift/red-moon#212]
It should be possible to define a recurring stop time without being forced to define a start time.
User scenario: Starting app manually, i.e. in dark during sleep, then at next usage (morning, bright light) with app still active, screen is barely readable. A scheduled stop time, i.e. wake up time, would circumvent this.
Kind of relates to issue #106

**Comment by smichel17** [comment]
This will be possible with #106, and I almost certainly will not do it before then, so I'm going to close this issue.

As a workaround, you can set your start time to 1 minute before the stop time.
