### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [LibreShift/red-moon#218]
Hi, this is about a contribution. Would you like to have a new logo design for the app? Just asking :)

**Comment by smichel17** [comment]
Hi, and thanks for the offer!

Short answer: I'm open to the possibility, and would be interested to see a quick sketch (or description in words, if you'd prefer) of what you're thinking before you create anything polished.

Long answer:..

In the past ~6 months I haven't had much time / chosen to spent it on Red Moon development. I am planning to return to it on the sooner side (within the month? We'll see..). In the meantime, I've noticed a couple other FLO screen filter apps on f-droid which *are* under active development.

It seems like a silly waste, to have several of us all working on essentially the same project. It's also been a long-term goal of mine to find other prior to be co-maintainers of Red Moon. So, before or when I return, I plan to reach out to those developers and discuss the possibility of merging our apps or just dropping development on all but one.

Getting back to your question: I'm happy with Red Moon's current icon, but if you have a better idea, I'd gladly switch that, too. But I also don't know whether the screen filter app I end up working on will be Red Moon or something else. I don't want to ask you to spend a bunch of time on an icon that may never be used.

Make of that what you will. At any rate, I'm definitely interesting in what idea(s) you have. :)

**Comment by ssnjrthegr8** [comment]
I see, OK then I will focus on some other project then :) Thank you for your time.

**Comment by smichel17** [comment]
Thanks for reaching out, it's always nice to get unsolicited offers to help.

I'm going to close this for now. If the app I end up working on is Red Moon, I'll ping here to see if you're still interested :)
