### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by smichel17** [LibreShift/red-moon#231]
It's been a while and I need to do this. Before that, I want to:

- [x] Update the changelog
- [x] Update the changelog format (#238)
- [x] Make the changelog show up in f-droid
- [x] Figure out why Travis isn't working sometimes
    - I was reading that Travis has had reliability issues lately and that CircleCI is the cool new hotness. I don't really care enough to migrate, but will help if someone else wants to take initiative.
- [x] Manually merge the good parts of #224
- [x] Wait until I will have enough time to quickly fix any bugs with the release (ie, a weekend).

**Comment by david-hil** [comment]
Yesterday, Travis failed on my PR with the same error message I had locally when trying to build. I fixed it by changing something in build.gradle that I found when googling the error message. Not sure what it actually does, but afterwards I could build the project.

**Comment by smichel17** [comment]
Was it adding the `google()` repository or something else?

**Comment by david-hil** [comment]
I think it was google(), but I can't check it right now
