### ISSUE TITLE
Red moon deactivates on playing a video in full screen mode

### ISSUE THREAD

**Issue by Sibasish** [LibreShift/red-moon#243]
I recently migrated to win 10 v1809. But I don't why somehow after setting up the laptop, whenever I open a video in full screen mode in any software, the external filter of the app deactivates. And upon minimizing the filter gets restored. 
    Why such a thing has happened now after all this time? This sort of thing didn't use to happen in win7/8 but has occurred now.

**Comment by NoahAndrews** [comment]
Red Moon is an Android app, you aren't using it on your Windows laptop.

**Comment by Sibasish** [comment]
Oh sorry, I meant to post the issue in other forum related to other
software. Fine thanks for the response.

**Comment by smichel17** [comment]
Out of curiosity, how did you end up at this repo? Similar name? Simple mistake (clicked the wrong bookmark or something like that)?

**Comment by Sibasish** [comment]
Similar function of the software.😀
