### ISSUE TITLE
Consider adding donation link

### ISSUE THREAD

**Issue by user8446** [LibreShift/red-moon#261]
For users that can't contribute code, consider adding a donation link so that users that get a lot out of the app can also help with development.

**Comment by smichel17** [comment]
I don't currently want to advertise a way to donate. However, we've been using Weblate for managing translations for many years for free; you could [donate to weblate](https://weblate.org/en/donate/).

As another alternative, you could [donate to Snowdrift.coop](https://snowdrift.coop/donate), another project that I am involved in and care about.

Finally, if you really just want to donate to me directly, contact me via email and we can figure something out.

**Comment by user8446** [comment]
Great, thank you

**Comment by smichel17** [comment]
Elaborating a little more:

- If you (or someone) can get together $1000 or so, I'll take a week after my current freelance project wraps up and dedicate it exclusively to Red Moon.
- For less than that, it's not going to affect my priorities, so I feel awkward taking money for nothing.
    - Of course, people could still give a "buy me a coffee", thank-you-style donation. But that's different than helping with development.
- I could take donations and keep track of them until they reach $1000, but then I have to keep track, which I don't really want to do. Also it could lead to weird expectations.

So for now I'd prefer to keep this mostly as a passion project, and people who would like to support the project can donate their time, instead. Note that I do have a couple easy ways to contribute listed [in the readme](https://github.com/LibreShift/red-moon#do-your-part--participate-in-the-community).
