### ISSUE TITLE
Feature request: an option to automatically disable in full screen apps

### ISSUE THREAD

**Issue by 07416** [LibreShift/red-moon#262]
I prefer to always view videos without the filter, especially since the color scheme is generally far more darker than typical webpages.

**Comment by smichel17** [comment]
Does the current feature to exclude specific apps not work for this case?

**Comment by 07416** [comment]
> 
> 
> Does the current feature to exclude specific apps not work for this case?

I'm really sorry, I missed this feature. I see my feature request now as mostly irrelevant, treat as you see fit.

**Comment by smichel17** [comment]
No problem. The one thing I am open to is adding more apps to the default block list (actually it's specific screens for the app, though there is nothing to clarify that). Right now it's just the package installer and proton mail's pin screen.
