### ISSUE TITLE
New quick tile icon?

### ISSUE THREAD

**Issue by mueller-ma** [LibreShift/red-moon#270]
**Is your feature request related to a problem? Please describe.**
With the latest update the Red Moon quick tile has a new icon. It looks like a stop icon inside a circle.

**Describe the solution you'd like**
Change it back to the old icon. IMO the old icon suits much better as it can be recognized as Red Moon. I don't understand what a stop icons means in this situation, especially because the stop icon is also shown if Red Moon isn't active.

**Comment by smichel17** [comment]
I'm not seeing this on my device or an emulator. I presume this is on Red Moon 3.5.0. What device and Android version are you using?

**Comment by mueller-ma** [comment]
Android 7, Red Moon 3.5.0.

**Comment by mueller-ma** [comment]
After a reboot, the old Red Moon icon is back.
