### ISSUE TITLE
Update Google Play store release & GitHub apks or remove prominent download links

### ISSUE THREAD

**Issue by smichel17** [LibreShift/red-moon#274]
With the release of v3.5.0, there's been an increase of people asking about when those updates will come to Google Play/GitHub. Previously @raatmarien did those releases, but he hasn't been actively involved with the project in a while (and there is the billing issue, #148). So I need to talk with him and decide on one of these options:

- @raatmarien becomes more active again, handles GitHub and GPlay releases.
- @raatmarien transfers the signing key and GPlay listing to me, and I take over those releases.
- We close the GPlay listing and remove the links from the readme.

There's some extra context in https://github.com/LibreShift/red-moon/issues/155#issuecomment-601296109.

**Comment by kujaw** [comment]
BTW - is this yours? https://play.google.com/store/apps/details?id=com.zerocode.redmoon.lite

**Comment by smichel17** [comment]
No, see https://github.com/LibreShift/red-moon/issues/214#issuecomment-363194282 (and please take follow-up conversation to that issue :)

In this particular case it doesn't look like they're doing anything malicious (eg, inserting ads/tracking), so I suspect they're just ignorant about licensing. So, before sending a DMCA takedown, I'd rather try a quick email asking them to follow the license and release the source under the GPLv3+ and say that it's based off this app (ie, link back here; it doesn't need to be prominent). Their email is public on the page, if someone else would like to do that.

**Comment by smichel17** [comment]
Update: They've since added ads, according to the reviews on that page, so I should also send a take-down notice there.

**Comment by smichel17** [comment]
I haven't heard from @raatmarien, but the [Google Play listing](https://play.google.com/store/apps/details?id=com.jmstudios.redmoon) seems to be no longer available, so that's that. I may put it back up on the Play Store, mostly to disincentivize the rip-offs. We'll see.
