### ISSUE TITLE
feature request: autostart at boot

### ISSUE THREAD

**Issue by sidmint** [LibreShift/red-moon#289]
Thank you for this useful app.
Autostart at boot option would be helpful for my weak battery and hardware which gets restarted automatically at times.

**Comment by smichel17** [comment]
This is already implemented —

- If you have the schedule enabled, the filter will start if it is during the scheduled period.
- If not, the filter will start if it was running when the phone shut down.

If it's not working, the most likely cause is your phone's battery manager preventing Red Moon from starting on boot. Try checking its settings.

**Comment by NoahAndrews** [comment]
> If it's not working, the most likely cause is your phone's battery manager preventing Red Moon from starting on boot. Try checking its settings.

See <dontkillmyapp.com> for more details on how to do this for your phone.

**Comment by sidmint** [comment]
Thank you, I selected "not optimised" in battery optimisation and now it works.
