### ISSUE TITLE
Some improvements to UI & widgets

### ISSUE THREAD

**Issue by shuvashish76** [LibreShift/red-moon#295]
https://user-images.githubusercontent.com/48226312/119297212-26eb8a00-bc78-11eb-81ea-02cb4334031f.mp4

(everything tested on the video mentioned below chronologically)
1. while moving the app on the home screen there is a white background behind the Red Moon logo. Just like other apps, it would look great if the "wolf" moves between the moon only.
2. when we toggle 2nd widget that is Red Moon Toggle there is a Red flash screen (check force stop app & toggle 2nd widget again) [probably android limitations, not a big issue]
>btw I love Red Moon "Lower system brightness" feature which is missing in [Night Screen](https://github.com/fython/Blackbulb) app. 💖

![new moon widget](https://user-images.githubusercontent.com/48226312/119297561-d9235180-bc78-11eb-8359-23207617f86e.jpeg)
3. Currently there are two widgets but both do the same job (2nd widget is for toggle on/off & 1st widget show its status only)
_few suggestions_
I) 1st widget looks a bit ugly now & I don't think a widget only for status purpose is worth
Make 1st widget a circular transparent wolf logo just like [Loop Habit tracker](https://github.com/iSoron/uhabits) app widget (check video) rename it to "Toggle Red Moon". & it should do the job of _current_ 2nd widget that is toggle on/off the Red Moon
![Screenshot_2021-05-26-18-04-56](https://user-images.githubusercontent.com/48226312/119660637-1cceb480-be4d-11eb-92e0-541f455408c0.jpeg)
![Screenshot_2021-05-26-18-05-21](https://user-images.githubusercontent.com/48226312/119660693-28ba7680-be4d-11eb-8460-81fd6c4fa523.jpeg)

II) & we should rename the 2nd widget to "Red Moon" only & clicking it should open up notification slider & should do the job of controlling Darkness, Colour & Opacity from system notification slider just like Night Screen app as mentioned in #294

**Comment by smichel17** [comment]
This is a bunch of things, so I'm going to convert it to a discussion.
