### ISSUE TITLE
Screen filters for eg colourblindness

### ISSUE THREAD

**Issue by hamishmb** [LibreShift/red-moon#321]
**Describe the solution you'd like**
Seeing as this app already has a filter, it makes sense to use it for colourblindness filters too, just as a suggestion.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by smichel17** [comment]
I don't know if that's possible. The filter works by putting a partially transparent red overlay over the whole screen. It just unconditionally makes everything darker/redder; it doesn't have the ability to see which colors are underneath and make different changes for different colors. The newly added, unreleased root mode has a little more control and might be useful here, but I'm not sure. It's still a whole-screen level of changing the intensity of certain colors.

It's also a little bit of scope creep for the app. The goal is to make night-time phone use less unpleasant.

What you might be able to do is emulate colorblindness. In other words, make it so a fully sighted person looking at the screen would have a similar experience to someone who is colorblind (by filtering out certain frequencies). But this is already possible in the phone's developer settings, so there's not much of a point there, either.

**Comment by hamishmb** [comment]
Ah, okay, so it's not quite as simple as I thought, and yeah it does sound like scope creep for sure, I just thought if the implementation was similar, then it might be worth a thought.
