### ISSUE TITLE
Material you theme on app

### ISSUE THREAD

**Issue by zoroya1** [LibreShift/red-moon#336]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

>Material you theme on Red moon will greatly elevate ux and ui of the app

**Describe the solution you'd like**

>changing interface of the app according to user's wallpaper.
Link : https://material.io/blog/announcing-material-you

**Describe alternatives you've considered**

>I've considered using Twilight app on play store but i would like to use Open source app as much as possible.

**Additional context**

**Comment by smichel17** [comment]
I'd happily accept a PR. But since I'm not doing any active development, the chance of me implementing this is near-zero.
